name: mi_billetera_universitaria
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.10.3
  provider: ^6.1.1
  intl: ^0.19.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.9.0
  shared_preferences: ^2.2.3
  local_auth: ^2.3.0  # Última versión estable
  flutter_secure_storage: ^9.2.4
  http: ^1.2.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_foreground: "assets/icons/adaptive-icon.png"
  adaptive_icon_background: "#1A237E"
  min_sdk_android: 21